apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: jmeter
    orgId: 1

datasources:
  - name: jmeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 5up3r-S3cr3t-auth-t0k3n
    jsonData:
      version: Flux
      organization: influxdata-org
      defaultBucket: jmeter_results
      tlsSkipVerify: true